import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidePanel } from "./components";
import { dummyThreads } from "./constants";
import { AppProvider } from "@shopify/polaris";
import { cookies } from "next/headers";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO: Shopify sets height: 100%, minHeight: 100% on html, body.
// Might need to come up with better approach(250827, sh)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ height: "100%", minHeight: "100%" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ height: "100%", minHeight: "100%" }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
